services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: edsjcbra
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: reboundrelay
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: